### PR TITLE
Added missing DEI bullet point and some links

### PR DESCRIPTION
**Pull request by sk8forether**
I added:
* A 4th bullet point to the Organizational Mission section that summarizes our DEI mission based on the [Mission](https://us-rse.org/about/mission/) and [DEI Mission Statement](https://us-rse.org/about/dei-mission/) pages, along with a sentence below the bullet list that links both of these pages for reference.
* A sentence to the Steering Committee Roles and Number section that links to the [Steering Committee Members](https://us-rse.org/about/steering-committee/) page

I also updated the date to today.

### CODE REVIEW

**Comment by sk8forether** [comment]
Also see [this PR](https://github.com/USRSE/usrse.github.io/pull/758) for some relevant discussion about the "Last Updated" date of pages such as this one.

**Comment by cmaimone** [comment]
Thanks for raising this.  We're going to consolidate this change with some other updates to make the document match current practices.  Because changes require steering committee approval, it's easier to bundle them.

**Comment by cmaimone** [comment]
This has been completed via a separate PR.

**Comment by sk8forether** [comment]
@cmaimone Can you please link the PR for posterity?

**Pull request closed without merging**
